services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command:
      - redis-server
      - '--requirepass'
      - isvahan2025
  postgres:
    image: postgres:15
    restart: always
    depends_on:
      - redis
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: isvahan2025
      POSTGRES_DB: compaire_db

volumes:
  postgres_data: null
  redis_data: null
